# -*- coding: utf-8 -*-
"""TIENDACCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M958V2XXQOegqfUuDNx5FeHeOIqJV_t
"""

def devuelta1(precio_total1, totaldinero):
    devuelta = totaldinero - precio_total1
    return devuelta

# Algoritmo Tienda_CCR
print("Bienvenido a la tienda CCR, por favor elija una opción")
inventario, cantidad, precio, producto, cliente = 0.0, 0.0, 0.0, 0.0, 0.0
precio_total, precio_total1 = 0.0, 0.0

print("1. Estudiante, tendrá un descuento del 5% en su compra")
print("2. Particular, no tendrá descuento")
cliente = int(input("Elija su tipo de cliente (1 o 2): "))

print("¿Qué desea comprar?")
print("1. Chicles = 1500")
print("2. Bombones = 700")
print("3. Café = 1500")
print("4. Sandwich = 3000")
print("5. Chocorramo = 2500")
print("6. Chuzo = 5000")
print("7. Arepa con queso = 4000")
producto = int(input("Ingrese el número del producto: "))

Chicle, Bombones, Cafe, Sandwich, Chocorramo, Chuzo, Arepa_queso = 1500, 700, 1500, 3000, 2500, 5000, 4000

print("Ingrese la cantidad del producto que desea comprar: ")
cantidad = int(input())

if cliente == 1:
    if producto == 1:
        precio_total = Chicle * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del chicle será de:", precio_total1)
    elif producto == 2:
        precio_total = Bombones * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del bombón será de:", precio_total1)
    elif producto == 3:
        precio_total = Cafe * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del café será de:", precio_total1)
    elif producto == 4:
        precio_total = Sandwich * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del sandwich será de:", precio_total1)
    elif producto == 5:
        precio_total = Chocorramo * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del chocorramo será de:", precio_total1)
    elif producto == 6:
        precio_total = Chuzo * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio del chuzo será de:", precio_total1)
    elif producto == 7:
        precio_total = Arepa_queso * (1 - 5 / 100)
        precio_total1 = precio_total * cantidad
        print("El precio de la arepa con queso será de:", precio_total1)
    else:
        print("No existe la opción ingresada")
else:
    if cliente == 2:
        if producto == 1:
            precio_total1 = Chicle * cantidad
            print("El valor del chicle será:", precio_total1)
        elif producto == 2:
            precio_total1 = Bombones * cantidad
            print("El valor del bombón será:", precio_total1)
        elif producto == 3:
            precio_total1 = Cafe * cantidad
            print("El valor del café será:", precio_total1)
        elif producto == 4:
            precio_total1 = Sandwich * cantidad
            print("El valor del sandwich será:", precio_total1)
        elif producto == 5:
            precio_total1 = Chocorramo * cantidad
            print("El valor del chocorramo será:", precio_total1)
        elif producto == 6:
            precio_total1 = Chuzo * cantidad
            print("El valor del chuzo será:", precio_total1)
        elif producto == 7:
            precio_total1 = Arepa_queso * cantidad
            print("El valor de la arepa con queso será:", precio_total1)
        else:
            print("No existe la opción ingresada")

print("Total a pagar por el cliente: ")
totaldinero = float(input())

print("La devuelta para el cliente será:", devuelta1(precio_total1, totaldinero))

comprar = 1
while comprar == 1:
    print("¿Desea seguir comprando?")
    print("1. Sí")
    print("2. No")
    comprar = int(input())
    if comprar == 1:
        print("Bienvenido de nuevo a la tienda CCR, por favor elija una opción")
        print("1. Estudiante, tendrá un descuento del 5% en su compra")
        print("2. Particular, no tendrá descuento")
        cliente = int(input("Elija su tipo de cliente (1 o 2): "))

        print("¿Qué desea comprar?")
        print("1. Chicles = 1500")
        print("2. Bombones = 700")
        print("3. Café = 1500")
        print("4. Sandwich = 3000")
        print("5. Chocorramo = 2500")
        print("6. Chuzo = 5000")
        print("7. Arepa con queso = 4000")
        producto = int(input("Ingrese el número del producto: "))

        print("Ingrese la cantidad del producto que desea comprar: ")
        cantidad = int(input())

        if cliente == 1:
            if producto == 1:
                precio_total = Chicle * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del chicle será de:", precio_total1)
            elif producto == 2:
                precio_total = Bombones * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del bombón será de:", precio_total1)
            elif producto == 3:
                precio_total = Cafe * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del café será de:", precio_total1)
            elif producto == 4:
                precio_total = Sandwich * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del sandwich será de:", precio_total1)
            elif producto == 5:
                precio_total = Chocorramo * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del chocorramo será de:", precio_total1)
            elif producto == 6:
                precio_total = Chuzo * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio del chuzo será de:", precio_total1)
            elif producto == 7:
                precio_total = Arepa_queso * (1 - 5 / 100)
                precio_total1 = precio_total * cantidad
                print("El precio de la arepa con queso será de:", precio_total1)
            else:
                print("No existe la opción ingresada")
        else:
            if cliente == 2:
                if producto == 1:
                    precio_total1 = Chicle * cantidad
                    print("El valor del chicle será:", precio_total1)
                elif producto == 2:
                    precio_total1 = Bombones * cantidad
                    print("El valor del bombón será:", precio_total1)
                elif producto == 3:
                    precio_total1 = Cafe * cantidad
                    print("El valor del café será:", precio_total1)
                elif producto == 4:
                    precio_total1 = Sandwich * cantidad
                    print("El valor del sandwich será:", precio_total1)
                elif producto == 5:
                    precio_total1 = Chocorramo * cantidad
                    print("El valor del chocorramo será:", precio_total1)
                elif producto == 6:
                    precio_total1 = Chuzo * cantidad
                    print("El valor del chuzo será:", precio_total1)
                elif producto == 7:
                    precio_total1 = Arepa_queso * cantidad
                    print("El valor de la arepa con queso será:", precio_total1)
                else:
                    print("No existe la opción ingresada")

        print("Total a pagar por el cliente: ")
        totaldinero = float(input())

        print("La devuelta para el cliente será:", devuelta1(precio_total1, totaldinero))

print("¡Muchas gracias por tu compra!")